[project]
name = "rag101"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "jupyter>=1.1.1",
    "ollama>=0.6.1",
    "pinecone>=6.0.0",
    "pypdf>=6.6.0",
    "python-dotenv>=1.2.1",
    "streamlit>=1.52.2",
]
